# Generated by Django 4.0.4 on 2022-05-03 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(help_text='RED', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_num', models.CharField(help_text='XS,S,M,L,XL,XXL so on', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='size',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='products',
            name='specifications',
            field=models.CharField(help_text='seperate it by ,', max_length=60, null=True),
        ),
    ]
