# Generated by Django 4.0.4 on 2022-05-03 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_attribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_attribute',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
